---
# Create a vpopmail user. This uses the 'vadduser' command, which is not idempotent -- it will
# throw an error if it's run on an existing user. This task has a 'creates' argument that
# should prevent repeated creation attempts. If for some reason you need to re-create a user,
# you'll have to manually remove the user's home directory and clean up the database.

- name: create user
  become: yes
  command: "/home/vpopmail/bin/vadduser -c '{{ comment }}' -q {{ quota }} {{ username }}@{{ domain }} {{ password }}"
  args:
    creates: "/home/vpopmail/domains/{{ domain }}/{{ username }}"

# If the user has the 'filter' flag set to true, create a .procmailrc file for that user
# that will contain a skeleton definition for procmail filtering.

- name: create procmailrc
  become: yes
  when: filter == True
  template:
    src: templates/dot_procmailrc.j2
    dest: /home/vpopmail/domains/{{ domain }}/.procmailrc-{{ username }}
    owner: vpopmail
    group: vchkpw
    mode: 0644

# If the user has the 'filter' flag set to true, create a .procmail directory for the
# user. The directory will hold the user's procmail log, and any include files.
-
- name: create procmail directory
  become: yes
  when: filter == True
  file:
    state: directory
    path: /home/vpopmail/domains/{{ domain }}/.procmail-{{ username }}
    owner: vpopmail
    group: vchkpw
    mode: 0755

# If the user has the 'filter' flag set to true, create a set of 'rc.*' files that
# will hold their procmail recipes.

- name: create procmail include files
  become: yes
  when: filter == True
  file:
    state: touch
    path: /home/vpopmail/domains/{{ domain }}/.procmail-{{ username }}/rc.{{ filterset }}
    owner: vpopmail
    group: vchkpw
    mode: 0644
  loop: "{{ filtersets }}"
  loop_control:
    loop_var: filterset

# If the user has some mail subdirectories specified as part of their definition, set
# those up.

- name: create mail directories
  become: yes
  file:
    state: touch
    path: /home/vpopmail/domains/{{ domain }}/{{ username }}/Maildir/{{ dir.0 }}/{{ dir.1 }}
    owner: vpopmail
    group: vchkpw
    mode: 0600
  loop: "{{ filterdirs|product(qmt_maildir_subdirs)|list }}"
  loop_control:
    loop_var: dir

# Write the .qmail file that will actually deliver mail to the user. The template will
# set up the file appropriately, so that it contains any relevant instructions, i.e. to
# use dspam, to use procmail filtering etc.

- name: write .qmail file
  become: yes
  template:
    src: templates/dot_qmail_user.j2
    dest: /home/vpopmail/domains/{{ domain }}/.qmail-{{ username }}
    owner: vpopmail
    group: vchkpw
    mode: 0644

