---
#- name: create user
#  become: yes
#  command: "/home/vpopmail/bin/vadduser {{ username }}@{{ domain }} {{ password }} -c {{ comment }}"
#  args:
#    creates: "/home/vpopmail/domains/{{ item.name }}"
#  vars:
#    ansible_ssh_pipelining: yes
#  with_items: "{{ qmt_domains }}"

- name: create user
  debug:
    msg: "Creating user {{ username }}@{{ domain }} with password {{ password }} -c {{ comment }}"

- name: create procmailrc
  when: filter == True
  template:
    src: templates/dot_procmailrc.j2
    dest: /home/vpopmail/domains/{{ domain }}/.procmailrc-{{ username }}
    owner: vpopmail
    group: vchkpw
    mode: 0644

- name: create procmail folder
  when: filter == True
  file:
    state: directory
    path: /home/vpopmail/domains/{{ domain }}/.procmail-{{ username }}
    owner: vpopmail
    group: vchkpw
    mode: 0755

- name: create procmail filtersets
  when: filter == True
  file:
    state: touch
    path: /home/vpopmail/domains/{{ domain }}/.procmail-{{ username }}/rc.{{ filterset }}
    owner: vpopmail
    group: vchkpw
    mode: 0644
  loop: "{{ filtersets }}"
  loop_control:
    loop_var: filterset

- name: write .qmail file
  debug:
    msg: "Writing /home/vpopmail/domains/{{ domain }}/.qmail-{{ username }}"
