- name: firewall -- start firewalld
  become: yes
  systemd:
    name: firewalld.service
    state: started
    enabled: yes

- name: firewall -- open ports
  become: yes
  firewalld:
    port: "{{ item }}/tcp"
    permanent: yes
    state: enabled
  with_items:
    - 20
    - 21
    - 22
    - 25
    - 80
    - 110
    - 113
    - 143
    - 443
    - 465
    - 587
    - 993
    - 995
    - 3306
  notify:
    - restart firewall
