---
# firewall setup
- name: firewall -- start firewalld
  become: yes
  systemd:
    name: firewalld.service
    state: started
    enabled: yes

- name: firewall -- open ports
  become: yes
  firewalld:
    port: "{{ item }}/tcp"
    permanent: yes
    state: enabled
  with_items: "{{ qmt_open_ports }}"
