---
# firewall setup
- name: firewall -- start firewalld
  become: yes
  systemd:
    name: firewalld.service
    state: started
    enabled: yes

- name: firewall -- open ports
  become: yes
  firewalld:
    port: "{{ item }}/tcp"
    permanent: yes
    state: enabled
  with_items:
    - 20
    - 21
    - 22
    - 25
    - 80
    - 110
    - 113
    - 143
    - 443
    - 465
    - 587
    - 993
    - 995
    - 3306
  register: ports

# This is ugly. Normally I'd just restart the firewall
# service. However, I've found that simply restarting the
# firewall leaves the server in a limbo state where it
# refuses all connections. Doing a full reboot seems to
# cure the issue.

- name: qt_install_centos_8 -- reboot server if needed
  become: yes
  when: ports.changed
  reboot:
