---
- include: qt_prep.yml
  tags:
    - qmt
- include: qt_install.yml
  tags:
    - qmt

# Additional configurations and tweaks

- include: httpd-ssl.yml
  tags:
    - ssl

- include: vpopmaild.yml
  when: qmt_install_vpopmaild | bool
  tags:
    - vpopmaild
    - roundcube

- include: roundcube.yml
  when: qmt_install_roundcube | bool
  tags:
    - roundcube

- include: rainloop.yml
  when: qmt_install_rainloop | bool
  tags:
    - rainloop

- include: php.yml
  tags:
    - rainloop
    - roundcube
