---
- name: install qmailtoaster for CentOS 7
  when: ansible_facts['distribution'] == 'CentOS' and ansible_facts['distribution_major_version'] == 7
  include: install_qmt_centos7.yml

- name: install qmailtoaster for CentOS 8
  when: ansible_facts['distribution'] == 'CentOS' and ansible_facts['distribution_major_version'] == 8
  include: install_qmt_centos8.yml
