---
# main

- debug:
    msg: Installing qmailtoaster on {{ inventory_hostname }} -- distribution={{ansible_facts['distribution']}} version={{ansible_facts['distribution_major_version']}}

# Do basic QMailToaster preparation
#
# Corresponds (roughly) to the 'qt_prep.sh' script used in CentOS 7 installation.

- when: ansible_facts['distribution_major_version'] == "7"
  include: qt_prep.yml
  tags:
    - qmt

# Set up the firewall
#
# Configure the firewall to open all ports required by qmailtoaster

- include: firewall.yml
  tags:
    - qmt

# Set up packages

- when: ansible_facts['distribution_major_version'] == "8"
  include: qt_package_setup_centos_8.yml
  tags:
    - qmt

- when: ansible_facts['distribution_major_version'] == "7"
  include: qt_package_setup_centos_7.yml
  tags:
    - qmt

# Set up web-related stuff

- include: php_configuration.yml
  tags:
    - qmt

- include: httpd_ssl.yml
  tags:
    - qmt

# Set up the database server and create the vpopmail database.

- when: ansible_facts['distribution_major_version'] == "8"
  include: qt_db_setup_centos_8.yml
  tags:
    - qmt

- when: ansible_facts['distribution_major_version'] == "7"
  include: qt_db_setup_centos_7.yml
  tags:
    - qmt

- include: qt_db_setup_security.yml
  tags:
    - qmt

- include: qt_db_setup_vpopmail_db.yml
  tags:
    - qmt

# Install qmailtoaster

- when: ansible_facts['distribution_major_version'] == "8"
  include: qt_install_centos_8.yml
  tags:
    - qmt

- when: ansible_facts['distribution_major_version'] == "7"
  debug:
    msg: "Installation of qmailtoaster for CentOS 7 not currently implemented."
  tags:
    - qmt

# Perform additional configuration for vpopmail

- include: vpopmail_setup.yml
  tags:
    - qmt

# Install roundcube

- when: ansible_facts['distribution_major_version'] == "7"
  debug:
    msg: "Installation of roundcube for CentOS 7 not currently implemented."
  tags:
    - qmt

- include: roundcube_setup.yml
  tags:
    - qmt

- debug:
    msg: "#DEBUG variable settings -- qmt_use_dspam={{ qmt_use_dspam }} qmt_install_rainloop={{ qmt_install_rainloop }}"

# Install dspam

- when: qmt_use_dspam == "yes"
  include: dspam_install.yml
  tags:
    - dspam

# Install rainloop

- when: qmt_install_rainloop == "yes"
  include: rainloop_install.yml
  tags:
    - rainloop

# Post-installation

- when: ansible_facts['distribution_major_version'] == "8"
  include: postinstall_centos_8.yml
  tags:
    - qmt

- when: ansible_facts['distribution_major_version'] == "7"
  include: postinstall_centos_7.yml
  tags:
    - qmt

- include: postinstall_tuning.yml
  tags:
    - qmt
# Do QMailToaster installation
#
# Corresponds (roughly) to the 'qt_install.sh' script.

#- include: qt_install.yml
#  tags:
#    - qmt
# # Set up a security certificate to replace the automatically-created
# # self-signed certificate.

# - include: httpd-ssl.yml
#   tags:
#     - ssl

# # Perform some checks to ensure that users, groups and directories
# # for vpopmail are all present.

# - include: vpopmail.yml
#   tags:
#     - vpopmail

# # Do an update to install additional software for the selected version
# # if necessary.

# - include: version.yml

# # Set up the vpopmaild daemon if required.

# - include: vpopmaild.yml
#   when: qmt_install_vpopmaild | bool
#   tags:
#     - vpopmaild
#     - roundcube

# # Install the Roundcube webmail package if required

# - include: roundcube.yml
#   when: qmt_install_roundcube | bool
#   tags:
#     - roundcube

# # Install the Rainloop webmail package if required

# - include: rainloop.yml
#   when: qmt_install_rainloop | bool
#   tags:
#     - rainloop

# # Adjust PHP settings if needed

# - include: php.yml
#   tags:
#     - rainloop
#     - roundcube

# # Add PHP7 patches

# - name: patch files for php7 if required
#   include: php7-patches.yml
#   when: qmt_php7_version != 0

# # Perform additional fine-tuning

# - include: tuning.yml

# # Set up domains

# - include: setup_domains.yml
#   tags:
#     - domains

# # Set up users

# - include: setup_users.yml
#   tags:
#     - users
