---

# Add the tools needed to manipulate MySQL from Python

- name: add python mysql support
  yum: name=MySQL-python state=present
  when: ansible_os_family == 'RedHat'

# Start MariaDB and ensure that it will be running on startup.

- name: start and enable mariadb
  systemd:
    name: mariadb
    enabled: yes
    state: started

# The following tasks take the place of 'mysql_secure_installation' in the original script. They
# perform the same basic functions, namely:
#
# - set the root password
# - remove the anonymous user
# - secure the root user
# - remove the test database
#
# Note that 'mariadb_root_password' is not defined in the 'vars' for this role. This is to force
# you to set it when you call the role. For security, it should be defined in an Ansible vault file.
#
# The tasks here are based on recommendations given at:
#
#    https://stackoverflow.com/questions/25136498/ansible-answers-to-mysql-secure-installation
#    https://coderwall.com/p/yez9yw/secure-mysql-with-ansible
#
# Note that the initial task to set the root password is set to ignore errors. This is
# to preserve idempotency; the script can be re-run repeatedly, and won't fail if the
# root password has already been set.

- name: set mariadb root password
  mysql_user: user=root password="{{ mariadb_root_password }}" host=localhost
  ignore_errors: yes

- name: remove anonymous user for all hosts
  when: qmt_switch.secure_mariadb
  mysql_user:
    name: ''
    host_all: yes
    state: absent
    login_user: root
    login_password: "{{ mariadb_root_password }}"

- name: secure the root user for this host
  when: qmt_switch.secure_mariadb
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mariadb_root_password }}"
    login_user: root
    login_password: "{{ mariadb_root_password }}"
  with_items:
    - "{{ inventory_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: remove the test database
  when: qmt_switch.secure_mariadb
  mysql_db:
    db: test
    state: absent
    login_user: root
    login_password: "{{ mariadb_root_password }}"

