---
- name: add REMI repo
  become: yes
  yum:
    name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present

- name: install php7
  become: yes
  yum:
    name:
      - php
      - php-mcrypt
      - php-cli
      - php-gd
      - php-curl
      - php-mysql
      - php-ldap
      - php-zip
      - php-fileinfo
    enablerepo: "remi-php{{ qmt_php7_version }}"
    state: latest
    update_cache: yes

