---
# perform additional post-installation tuning

- name: postinstall_tuning -- set SPF behavior
  become: yes
  template:
    src: spfbehavior.j2
    dest: /var/qmail/control/spfbehavior
    owner: root
    group: qmail
    mode: "0644"

- name: postinstall_tuning -- create spamassassin data directory
  become: yes
  file:
    path: "{{ qmt_clamscan_home_dir }}/.spamassassin"
    state: directory
    owner: clamscan
    group: clamscan
    mode: 0755
