---
# perform additional post-installation tuning

- name: postinstall_tuning -- set SPF behavior
  become: yes
  template:
    src: spfbehavior.j2
    dest: /var/qmail/control/spfbehavior
    owner: root
    group: qmail
    mode: "0644"

# On creation, 'clamscan' has a default home directory of '/'. This seems
# to result in errors when spamassassin -- which runs as 'clamscan' -- tries
# to write preferences to '//.spamassassin/user_prefs'. Changing the
# home directory for 'clamscan' and creating a directory with the
# write permissions should take care of this.

- name: postinstall_tuning -- create spamassassin data directory
  become: yes
  file:
    path: /home/vpopmail/.spamassassin
    state: directory
    owner: clamscan
    group: clamscan
    mode: 0755

- name: postinstall_tuning -- check clamscan home directory
  become: yes
  shell: 'cat /etc/passwd | grep clamscan | awk -F ":" ''{print $6}'''
  register: clamscan_home

- name: DEBUG
  debug:
    msg: "{{ clamscan_home }}"

- name: postinstall_tuning -- halt clamscan if needed
  when: clamscan_home.stdout != "{{ qmt_clamscan_home_dir }}"
  become: yes
  systemd:
    name: "clamd@scan"
    state: stopped

- name: postinstall_tuning -- change clamscan home directory
  when: clamscan_home.stdout != "{{ qmt_clamscan_home_dir }}"
  become: yes
  user:
    name: clamscan
    home: "{{ qmt_clamscan_home_dir }}"

- name: postinstall_tuning -- start clamscan if needed
  when: clamscan_home.stdout != "{{ qmt_clamscan_home_dir }}"
  become: yes
  systemd:
    name: "clamd@scan"
    state: started
