---
- name: qt_db_setup_vpopmail_db -- check if vpopmail database exists
  when: qmt_vpopmail_rebuild_database
  shell: "mysql -u root -p{{ qmt_db_root_password}} -e 'SHOW DATABASES;' | grep 'vpopmail'"
  register: dbstatus
  failed_when: dbstatus.rc == 2

- name: qt_db_setup_vpopmail_db -- dump vpopmail database if it exists
  mysql_db:
    login_user: root
    login_password: "{{ qmt_db_root_password}}"
    name: vpopmail
    state: dump
    target: "{{ qmt_vpopmail_dump_file_path }}"
  when: qmt_vpopmail_rebuild_database and dbstatus.rc == 0

- name: qt_db_setup_vpopmail_db -- drop vpopmail database if it exists
  mysql_db:
    login_user: root
    login_password: "{{ qmt_db_root_password}}"
    name: vpopmail
    state: absent
  when: qmt_vpopmail_rebuild_database and dbstatus.rc == 0

- name: qt_db_setup_vpopmail_db -- ensure vpopmail database is present
  mysql_db:
    login_user: root
    login_password: "{{ qmt_db_root_password}}"
    name: vpopmail
    state: present

- name: qt_db_setup_vpopmail_db -- reload mysql
  shell: "mysqladmin -uroot -p{{ qmt_db_root_password}} reload"

- name: qt_db_setup_vpopmail_db -- refresh mysql
  shell: "mysqladmin -uroot -p{{ qmt_db_root_password}} refresh"

- name: qt_db_setup_vpopmail_db -- create vpopmail database user and assign privileges
  mysql_user:
    login_user: root
    login_password: "{{ qmt_db_root_password}}"
    name: vpopmail
    password: "{{ qmt_db_vpopmail_password}}"
    priv: "vpopmail.*:ALL"
    state: present

- name: qt_db_setup_vpopmail_db -- reload mysql
  shell: "mysqladmin -uroot -p{{ qmt_db_root_password}} reload"

- name: qt_db_setup_vpopmail_db -- refresh mysql
  shell: "mysqladmin -uroot -p{{ qmt_db_root_password}} refresh"
