---
# Set up the database for CentOS 8

- name: qt_db_setup_centos_8 -- set up dnf variables
  become: yes
  template:
    src: templates/etc_yum_vars_db.j2
    dest: /etc/yum/vars/db
    mode: 0644

- name: qt_db_setup_centos_8 -- get name of db daemon
  set_fact:
    qmt_database_daemon: "{{ (qmt_database == 'mysql') | ternary ('mysqld', 'mariadb') }}"

- name: qt_db_setup_centos_8 -- install selected database
  become: yes
  yum:
    name:
      [
        "{{ qmt_database }}",
        "{{ qmt_database }}-server",
        "{{ qmt_database }}-devel",
      ]
    state: latest

- name: qt_db_setup_centos_8 -- install MySQL Python
  become: yes
  yum:
    name: "python3-mysql"
    enablerepo: "epel"
    state: latest

- name: qt_db_setup_centos_8 -- write credentials file
  template:
    src: templates/sql_cnf.j2
    dest: "{{ qmt_db_credfile }}"
    mode: 0644

- name: qt_db_setup_centos_8 -- start and enable database server
  become: yes
  systemd:
    name: "{{ qmt_database_daemon }}.service"
    enabled: yes
    state: started
