---
- name: install php5
  include: php5.yml
  when: qmt_php7_version == 0

- name: install php7
  include: php7.yml
  when: qmt_php7_version != 0

- name: start mariadb
  become: yes
  systemd:
    name: mariadb.service
    state: started
    enabled: yes

- name: initialize mariadb
  include: mariadb.yml

- name: check if vpopmail database exists
  when: qmt_vpopmail_rebuild_database
  shell: "mysql -u root -p{{ qmt_db_root_password}} -e 'SHOW DATABASES;' | grep 'vpopmail'"
  register: dbstatus
  failed_when: dbstatus.rc == 2

- name: dump vpopmail database if it exists
  mysql_db:
    login_user: root
    login_password: "{{ qmt_db_root_password}}"
    name: vpopmail
    state: dump
    target: "{{ qmt_vpopmail_dump_file_path }}"
  when: qmt_vpopmail_rebuild_database and dbstatus.rc == 0

- name: drop vpopmail database if it exists
  mysql_db:
    login_user: root
    login_password: "{{ qmt_db_root_password}}"
    name: vpopmail
    state: absent
  when: qmt_vpopmail_rebuild_database and dbstatus.rc == 0

- name: ensure vpopmail database is present
  mysql_db:
    login_user: root
    login_password: "{{ qmt_db_root_password}}"
    name: vpopmail
    state: present

- name: reload mysql
  shell: "mysqladmin -uroot -p{{ qmt_db_root_password}} reload"

- name: refresh mysql
  shell: "mysqladmin -uroot -p{{ qmt_db_root_password}} refresh"

- name: create vpopmail database user and assign privileges
  mysql_user:
    login_user: root
    login_password: "{{ qmt_db_root_password}}"
    name: vpopmail
    password: "{{ qmt_db_vpopmail_password}}"
    priv: "vpopmail.*:ALL"
    state: present

- name: reload mysql
  shell: "mysqladmin -uroot -p{{ qmt_db_root_password}} reload"

- name: refresh mysql
  shell: "mysqladmin -uroot -p{{ qmt_db_root_password}} refresh"

- name: install dependencies
  become: yes
  yum:
    name:
      [
        "daemontools",
        "ucspi-tcp",
        "libsrs2",
        "libsrs2-devel",
        "vpopmail",
        "spamdyke",
        "qmail",
        "autorespond",
        "control-panel",
        "ezmlm",
        "ezmlm-cgi",
        "qmailadmin",
        "qmailmrtg",
        "maildrop",
        "maildrop-devel",
        "isoqlog",
        "vqadmin",
        "squirrelmail",
        "spamassassin",
        "clamav",
        "ripmime",
        "simscan",
        "mailman",
        "mailman-debuginfo",
        "dovecot",
        "libdomainkeys-devel",
        "qmt-plus",
      ]
    state: latest
    update_cache: yes
    disablerepo:
      - ius

- name: ensure /home/vpopmail/etc exists
  become: yes
  file:
    path: /home/vpopmail/etc
    state: directory
    owner: vpopmail
    group: vchkpw
    mode: "0755"

- name: write vpopmail.mysql
  become: yes
  template:
    src: vpopmail.mysql.j2
    dest: /home/vpopmail/etc/vpopmail.mysql
    backup: yes
    owner: vpopmail
    group: vchkpw
    mode: "0644"

- name: stop qmail
  become: yes
  shell: "qmailctl stop &> /dev/null"

- name: start qmail
  become: yes
  shell: "qmailctl start &> /dev/null"

- name: stop freshclam
  become: yes
  service:
    name: freshclam
    state: stopped

- name: set up ownership of clamav
  become: yes
  file:
    path: /run/clamav
    owner: root
    group: clamav
    mode: "0775"

- name: start and enable services
  become: yes
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - clamav-daemon.socket
    - clamav-daemon.service
    - clamav-freshclam
    - spamd
    - dovecot
    - httpd
    - named
    - vsftpd
    - network
    - acpid
    - atd
    - autofs
    - crond
    - ntpd
    - smartd
    - sshd
    - irqbalance

- name: start isoqlog
  become: yes
  shell: sh /usr/share/toaster/isoqlog/bin/cron.sh

- name: enable NetworkManager
  become: yes
  systemd:
    name: NetworkManager-wait-online.service
    enabled: yes

- name: disable chronyd
  become: yes
  systemd:
    name: chronyd.service
    enabled: no
  ignore_errors: yes

- name: get toaststat
  become: yes
  get_url:
    url: https://raw.githubusercontent.com/qmtoaster/scripts/master/toaststat
    dest: /usr/bin/toaststat
    mode: "0755"

- name: install dspam
  include: dspam.yml
  when: qmt_use_dspam | bool
  tags:
    - dspam

- name: add man pages
  become: yes
  lineinfile:
    path: /etc/man_db.conf
    line: "MANDATORY_MANPATH /var/qmail/man"
    state: present
    regexp: EOF

- name: set up tcp.smtp
  become: yes
  template:
    src: tcp_smtp.j2
    dest: /etc/tcprules.d/tcp.smtp
    backup: yes
    owner: root
    group: root
    mode: "0644"
  notify:
    - rebuild qmail cdb

- name: install local squirrelmail config
  become: yes
  template:
    src: squirrelmail_config_local.php.j2
    dest: /etc/squirrelmail/config_local.php
    backup: yes
    owner: root
    group: root
    mode: "0644"
