---
# install qmailtoaster on CentOS 8

- name: qt_install_centos_8 -- add qmt repo
  become: yes
  get_url:
    url: https://raw.githubusercontent.com/qmtoaster/mirrorlist/master/qmt-centos8.repo
    dest: /etc/yum.repos.d/qmt.repo
    owner: root
    group: root
    mode: "0644"

- name: qt_install_centos_8 -- install qmailtoaster
  become: yes
  yum:
    name:
      [
        "daemontools",
        "ucspi-tcp",
        "libsrs2",
        "libsrs2-devel",
        "vpopmail",
        "spamdyke",
        "simscan",
        "qmail",
        "autorespond",
        "control-panel",
        "ezmlm",
        "ezmlm-cgi",
        "qmailadmin",
        "qmailmrtg",
        "maildrop",
        "maildrop-devel",
        "isoqlog",
        "vqadmin",
        "squirrelmail",
        "clamav",
        "ripmime",
        "dovecot",
        "qmt-plus",
      ]
    state: latest

- name: qt_install_centos_8 -- install clamav from epel
  become: yes
  yum:
    name: ["clamav", "clamav-update", "clamd"]
    enablerepo: epel
    disablerepo: qmt

- name: qt_install_centos_8 -- fetch clamd@scan.service
  become: yes
  get_url:
    url: https://raw.githubusercontent.com/qmtoaster/scripts/master/clamd@scan.service
    dest: /usr/lib/systemd/system/clamd@scan.service
    owner: root
    group: root
    mode: "0644"

- name: qt_install_centos_8 -- fetch clamd@scan.service
  become: yes
  get_url:
    url: https://raw.githubusercontent.com/qmtoaster/scripts/master/scan.conf
    dest: /etc/clamd.d/scan.conf
    owner: root
    group: root
    mode: "0644"

- name: qt_install_centos_8 -- verify ownership of files
  become: yes
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - {
        path: "/var/qmail/simscan",
        owner: "clamscan",
        group: "root",
        mode: 0750,
      }
    - {
        path: "/var/qmail/bin/simscan",
        owner: "clamscan",
        group: "root",
        mode: 04711,
      }

- name: qt_install_centos_8 -- verify state of clamav directories
  become: yes
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: 0755
  with_items:
    - { path: "/var/log/clamd", owner: "clamscan", group: "clamscan" }
    - { path: "/var/log/clamav", owner: "clamupdate", group: "clamupdate" }
    - { path: "/var/lib/clamav", owner: "clamupdate", group: "clamupdate" }

- name: qt_install_centos_8 -- edit /etc/freshclam.conf
  become: yes
  lineinfile:
    path: /etc/freshclam.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - {
        regexp: "^#?UpdateLogFile",
        line: "UpdateLogFile /var/log/clamav/freshclam.log",
      }
    - { regexp: "^#?LogFileMaxSize", line: "LogFileMaxSize 2M" }
    - { regexp: "^#?LogTime", line: "LogTime yes" }
    - { regexp: "^#?LogVerbose", line: "LogVerbose yes" }
    - { regexp: "^#?LogRotate", line: "LogRotate yes" }
  register: freshclam_conf

- name: qt_install_centos_8 -- run freshclam if needed
  become: yes
  when: freshclam_conf.changed
  command: freshclam

- name: qt_install_centos_8 -- add qmailtoaster man pages to man_db.conf
  become: yes
  lineinfile:
    path: /etc/man_db.conf
    regexp: "/var/qmail/man"
    line: MANDATORY_MANPATH /var/qmail/man

- name: qt_install_centos_8 -- bring up qmail
  become: yes
  command: qmailctl start

- name: qt_install_centos_8 -- enable all services
  become: yes
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - clamd@scan
    - clamav-freshclam
    - dovecot
    - spamassassin
    - httpd
    - chronyd
    - acpid
    - atd
    - autofs
    - smartd

- name: qt_install_centos_8 -- install toaststat
  become: yes
  get_url:
    url: https://raw.githubusercontent.com/qmtoaster/scripts/master/toaststat.cos8
    dest: /usr/bin/toaststat
    owner: root
    group: root
    mode: "0755"

- name: qt_install_centos_8 -- edit /usr/bin/toaststat
  become: yes
  lineinfile:
    path: /usr/bin/toaststat
    regexp: "^CLAMD="
    line: "CLAMD=clamd@scan.service"
  with_items:
    - { regexp: "^CLAMS=", line: "" }
    - { regexp: "^CLAMD=", line: "CLAMD=clamd@scan.service" }
    - {
        regexp: "^for sv in",
        line: "for sv in $CLAMD clamav-freshclam spamassassin dovecot $DBD httpd $NAMED chronyd sshd crond $VSFTPD acpid atd autofs smartd $IRQBALANCE",
      }

- name: qt_install_centos_8 -- start toaststat
  become: yes
  command: toaststat

- name: qt_install_centos_8 -- set up ACL for admin tools
  become: yes
  lineinfile:
    path: /etc/httpd/conf/toaster.conf
    regexp: "Define aclnet"
    line: Define aclnet "{{ qmt_toast_aclnet }}"
