---
# install qmailtoaster on CentOS 8

- name: qt_install_centos_8 -- add qmt repo
  become: yes
  get_url:
    url: https://raw.githubusercontent.com/qmtoaster/mirrorlist/master/qmt-centos8.repo
    dest: /etc/yum.repos.d/qmt.repo
    owner: root
    group: root
    mode: "0644"

- name: qt_install_centos_8 -- install qmailtoaster
  become: yes
  yum:
    name:
      [
        "daemontools",
        "ucspi-tcp",
        "libsrs2",
        "libsrs2-devel",
        "vpopmail",
        "spamdyke",
        "simscan",
        "qmail",
        "autorespond",
        "control-panel",
        "ezmlm",
        "ezmlm-cgi",
        "qmailadmin",
        "qmailmrtg",
        "maildrop",
        "maildrop-devel",
        "isoqlog",
        "vqadmin",
        "squirrelmail",
        "clamav",
        "ripmime",
        "dovecot",
        "qmt-plus",
      ]
    state: latest

# - name: make symbolic link from sendmail
#   become: yes
#   file:
#     src: /usr/sbin/sendmail
#     dest: /var/qmail/bin/sendmail
#     owner: root
#     group: root
#     state: link

- name: qt_install_centos_8 -- add qmailtoaster man pages to man_db.conf
  become: yes
  lineinfile:
    path: /etc/man_db.conf
    regexp: "/var/qmail/man"
    line: MANDATORY_MANPATH /var/qmail/man

- name: qt_install_centos_8 -- bring up qmail
  become: yes
  command: qmailctl start

- name: qt_install_centos_8 -- enable all services
  become: yes
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - clamav-daemon.service
    - clamav-daemon.socket
    - clamav-freshclam
    - dovecot
    - spamassassin
    - httpd
    - chronyd
    - acpid
    - atd
    - autofs
    - smartd

- name: qt_install_centos_8 -- install toaststat
  become: yes
  get_url:
    url: https://raw.githubusercontent.com/qmtoaster/scripts/master/toaststat.cos8
    dest: /usr/bin/toaststat
    owner: root
    group: root
    mode: "0755"

- name: qt_install_centos_8 -- start toaststat
  become: yes
  command: toaststat

- name: qt_install_centos_8 -- set up ACL for admin tools
  become: yes
  lineinfile:
    path: /etc/httpd/conf/toaster.conf
    regexp: "Define aclnet"
    line: Define aclnet "{{ qmt_toast_aclnet }}"
