---
# perform basic preparation tasks before installation

- name: qt_prep -- disable selinux
  become: yes
  selinux:
    state: disabled
  register: selinux_disabled

- name: qt_prep -- yum clean
  become: yes
  shell: yum clean all
  args:
    warn: no

- name: qt_prep -- yum update
  become: yes
  yum:
    name: "*"
    state: latest
    update_cache: yes

- name: qt_prep -- install wget
  become: yes
  yum:
    name: wget
    state: latest

# Judging by Eric's scripts, it's only necessary to reboot the server after
# disabling SELinux on CentOS 7.

- name: qt_prep -- reboot when required
  when: ansible_facts['distribution_major_version'] == "7" and selinux_disabled
  reboot:
