---
# set up required supporting packages on CentOS 8

- name: qt_package_setup_centos_8 -- yum update
  become: yes
  yum:
    name: "*"
    state: latest
    update_cache: yes

- name: qt_package_setup_centos_8 -- enable EPEL Repository on CentOS 8
  become: yes
  dnf:
    name: epel-release
    state: latest

- name: qt_package_setup_centos_8 -- get Remi's GPG keys
  become: yes
  rpm_key:
    state: present
    key: "{{ item.url }}"
    fingerprint: "{{ item.fingerprint }}"
  with_items:
    - {
        url: https://rpms.remirepo.net/RPM-GPG-KEY-remi2020,
        fingerprint: "34C1 0BDB CC6F 1B25 2E50  BA1A 0714 919E 4C21 A808",
      }
    - {
        url: https://rpms.remirepo.net/RPM-GPG-KEY-remi2019,
        fingerprint: "5F13 6145 BF10 369B 7685  D8DE 5036 66CC BBAE 6F1B",
      }
    - {
        url: https://rpms.remirepo.net/RPM-GPG-KEY-remi2018,
        fingerprint: "6B38 FEA7 231F 87F5 2B9C  A9D8 5550 9759 5F11 735A",
      }
    - {
        url: https://rpms.remirepo.net/RPM-GPG-KEY-remi2017,
        fingerprint: "44E8 9CD5 B233 62C2 24CE  5A5D E080 F29F 0364 B949",
      }
    - {
        url: https://rpms.remirepo.net/RPM-GPG-KEY-remi,
        fingerprint: "1EE0 4CCE 88A4 AE4A A29A  5DF5 004E 6F47 00F9 7F56",
      }

- name: qt_package_setup_centos_8 -- install remi-release-8
  become: yes
  yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm

- name: qt_package_setup_centos_8 -- update all
  become: yes
  dnf:
    name: "*"
    state: latest

- name: qt_package_setup_centos_8 -- install dnf-utils
  become: yes
  dnf:
    name: dnf-utils
    state: latest

- name: qt_package_setup_centos_8 -- install Remi's PHP 7
  become: yes
  command: dnf -y module install php:remi-7.4
  args:
    warn: no

- name: qt_package_setup_centos_8 -- install additional packages
  become: yes
  yum:
    name:
      [
        "logwatch",
        "bind",
        "bind-utils",
        "telnet",
        "yum-utils",
        "chrony",
        "acpid",
        "at",
        "autofs",
        "smartmontools",
        "wget",
        "vsftpd",
        "mod_ssl",
        "fail2ban",
        "roundcubemail",
        "php-mysql",
      ]
    enablerepo: remi
