---
- name: yum update
  become: yes
  yum:
    name: "*"
    state: latest
    update_cache: yes

- name: Enable EPEL Repository on CentOS 8
  become: yes
  dnf:
    name: epel-release
    state: latest

- name: Enable Remi's repo
  become: yes
  yum_repository:
    name: remi
    description: Remi Release 8
    baseurl: https://rpms.remirepo.net/enterprise/remi-release-8.rpm

- name: clean dnf
  become: yes
  command: dnf clean all && rm -r /var/cache/dnf

- name: update all
  become: yes
  dnf:
    name: "*"
    state: latest

- name: Install dnf-utils
  become: yes
  dnf:
    name: dnf-utils
    state: latest

- name: Install Remi's PHP 7
  become: yes
  dnf:
    name: "@php:remi-7.4"
    state: latest

- name: Install additional packages
  become: yes
  yum:
    name:
      [
        "logwatch",
        "bind",
        "bind-utils",
        "telnet",
        "yum-utils",
        "chrony",
        "acpid",
        "at",
        "autofs",
        "smartmontools",
        "wget",
        "vsftpd",
        "mod_ssl",
        "fail2ban",
        "roundcubemail",
        "php-mysql",
      ]
    enablerepo: remi
