---
- name: remove postfix
  become: yes
  yum:
    name: postfix
    state: absent

- name: add EPEL repository
  become: yes
  yum:
    name: epel-release
    state: latest

- name: install yum-plugin-priorities
  become: yes
  yum:
    name: yum-plugin-priorities
    state: latest

- name: get qmailtoaster rpm
  get_url:
    url: https://github.com/qmtoaster/release/raw/master/qmt-release-{{ qmt_version }}.qt.el7.noarch.rpm
    dest: /tmp/qmt-release-{{ qmt_version }}.qt.el7.noarch.rpm

- name: install qmailtoaster rpm
  become: yes
  yum:
    name: /tmp/qmt-release-{{ qmt_version }}.qt.el7.noarch.rpm
    state: present

- name: install required packages for CentOS 7
  become: yes
  yum:
    name:
      [
        "rsync",
        "bind-utils",
        "bind",
        "net-tools",
        "zlib-devel",
        "mariadb-server",
        "mariadb",
        "mariadb-devel",
        "libev-devel",
        "httpd",
        "mrtg",
        "expect",
        "libidn-devel",
        "aspell",
        "tmpwatch",
        "perl-Time-HiRes",
        "perl-ExtUtils-MakeMaker",
        "perl-Archive-Tar",
        "perl-Digest-SHA",
        "perl-HTML-Parser",
        "perl-IO-Zlib",
        "perl-Net-DNS",
        "perl-NetAddr-IP",
        "perl-Crypt-OpenSSL-Bignum",
        "perl-Digest-SHA1",
        "perl-Encode-Detect",
        "perl-Geo-IP",
        "perl-IO-Socket-SSL",
        "perl-Mail-DKIM",
        "perl-Razor-Agent",
        "perl-Sys-Syslog",
        "perl-Net-CIDR-Lite",
        "perl-DB_File",
        "bzip2-devel",
        "check-devel",
        "curl-devel",
        "gmp-devel",
        "ncurses-devel",
        "libxml2-devel",
        "python-devel",
        "sqlite-devel",
        "postgresql-devel",
        "openldap-devel",
        "quota-devel",
        "libcap-devel",
        "pam-devel",
        "clucene-core-devel",
        "expat-devel",
        "emacs",
        "ocaml",
        "procmail",
        "wget",
        "logwatch",
        "vsftpd",
        "acpid",
        "acpid-sysvinit",
        "at",
        "autofs",
        "ntp",
        "smartmontools",
        "mod_ssl",
        "fail2ban",
        "perl-Sys-Hostname-Long",
        "perl-Mail-DomainKeys",
        "perl-Mail-SPF-Query",
        "nfs-utils",
        "bzip2",
        "python2-PyMySQL",
      ]
    state: latest
    update_cache: yes
    disablerepo:
      - ius
