---
- name: disable selinux
  when: ansible_facts['distribution'] == 'CentOS' and ansible_facts['distribution_major_version'] == 7
  become: yes
  selinux:
    state: disabled
  notify:
    - reboot server

- name: yum clean
  become: yes
  shell: yum clean all
  args:
    warn: no

- name: yum update
  become: yes
  yum:
    name: "*"
    state: latest
    update_cache: yes

- name: install wget
  when: ansible_facts['distribution'] == 'CentOS' and ansible_facts['distribution_major_version'] == 7
  become: yes
  yum:
    name: wget
    state: latest

- name: flush handlers
  meta: flush_handlers
