---
- name: create rainloop directory
  become: yes
  file:
    path: /usr/share/rainloop/
    state: directory
    mode: '0755'

- name: get the rainloop sources [community version]
  become: yes
  when: qmt_rainloop_license == 'community'
  unarchive:
    src: https://www.rainloop.net/repository/webmail/rainloop-community-latest.zip
    dest: /usr/share/rainloop/
    remote_src: yes

- name: get the rainloop sources [standard version]
  become: yes
  when: qmt_rainloop_license == 'standard'
  unarchive:
    src: https://www.rainloop.net/repository/webmail/rainloop-latest.zip
    dest: /usr/share/rainloop/
    remote_src: yes

- name: change file modes recursively
  become: yes
  command: |
    chmod -c -R ug=rw,o=r,a-x+X /usr/share/rainloop
  args:
    warn: false
  register: chmod_status
  changed_when: chmod_status.stdout != ""

- name: change file ownership
  become: yes
  command: |
    chown -c -R apache:apache /usr/share/rainloop
  args:
    warn: false
  register: chown_status
  changed_when: chown_status.stdout != ""

- name: create configuration file
  become: yes
  template:
    src: rainloop_centos_7_conf.j2
    dest: /etc/httpd/conf.d/rainloop.conf
    backup: yes
    owner: apache
    group: apache
    mode: '0644'
  notify:
    - restart apache

- name: create rainloop domain files
  become: yes
  template:
    src: rainloop_domain_ini.j2
    dest: "/usr/share/rainloop/data/_data_/_default_/domains/{{ item.domain }}.ini"
    backup: yes
    owner: apache
    group: apache
    mode: '0644'
  with_items: "{{ qmt_rainloop_domains }}"

- name: warn about configuration
  debug:
    msg: "To complete Rainloop configuration, visit 'https://yourserver/rl/?admin/' and log in with user 'admin' and password '12345'. Remember to change the admin password immediately."
