---
- name: create rainloop directory
  become: yes
  file:
    path: /usr/share/rainloop/
    state: directory
    mode: '0755'

- name: get the rainloop sources [community version]
  become: yes
  when: qmt_rainloop_license == 'community'
  unarchive:
    src: https://www.rainloop.net/repository/webmail/rainloop-community-latest.zip
    dest: /usr/share/rainloop/
    remote_src: yes

- name: get the rainloop sources [standard version]
  become: yes
  when: qmt_rainloop_license == 'standard'
  unarchive:
    src: https://www.rainloop.net/repository/webmail/rainloop-latest.zip
    dest: /usr/share/rainloop/
    remote_src: yes

- name: change file modes recursively
  become: yes
  command: |
    chmod -c -R ug=rw,o=r,a-x+X /usr/share/rainloop
  args:
    warn: false
  register: chmod_status
  changed_when: chmod_status.stdout != ""

- name: change file ownership
  become: yes
  command: |
    chown -c -R apache:apache /usr/share/rainloop
  args:
    warn: false
  register: chown_status
  changed_when: chown_status.stdout != ""

- name: create configuration file
  become: yes
  template:
    src: rainloop_centos_7_conf.j2
    dest: /etc/httpd/conf.d/rainloop.conf
    backup: yes
    owner: apache
    group: apache
    mode: '0644'
  notify:
    - restart apache

- name: create rainloop data directories
  become: yes
  file:
    path: /usr/share/rainloop/data/_data_/_default_/{{ item }}
    state: directory
    owner: apache
    group: apache
    mode: '0755'
  with_items:
    - cache
    - configs
    - domains
    - logs
    - plugins
    - storage

- name: create rainloop domain files
  become: yes
  template:
    src: rainloop_domain_ini.j2
    dest: "/usr/share/rainloop/data/_data_/_default_/domains/{{ item.domain }}.ini"
    backup: yes
    owner: apache
    group: apache
    mode: '0644'
  with_items: "{{ qmt_rainloop_domains }}"

- name: create application configuration file
  become: yes
  template:
    src: rainloop_application_ini.j2
    dest: /usr/share/rainloop/data/_data_/_default_/configs/application.ini
    backup: yes
    owner: apache
    group: apache
    mode: '0644'
  register: wrote_application_ini_file

- name: change admin password - step 1
  when: wrote_application_ini_file.changed and qmt_rainloop_admin_password != '12345'
  become: yes
  template:
    src: rainloop_set_password_php.j2
    dest: /tmp/rainloop_set_password.php
    owner: apache
    group: apache
    mode: '0644'

- name: change admin password - step 2
  when: wrote_application_ini_file.changed and qmt_rainloop_admin_password != '12345'
  become: yes
  shell: php /tmp/rainloop_set_password.php

- name: change admin password - step 3
  when: wrote_application_ini_file.changed and qmt_rainloop_admin_password != '12345'
  become: yes
  file:
    path: /tmp/rainloop_set_password.php
    state: absent

