---
- name: get the rainloop sources [community version]
  become: yes
  when: qmt_rainloop_license == 'community'
  unarchive:
    src: https://www.rainloop.net/repository/webmail/rainloop-community-latest.zip
    dest: /usr/share/
    remote_src: yes

- name: get the rainloop sources [standard version]
  become: yes
  when: qmt_rainloop_license == 'standard'
  unarchive:
    src: https://www.rainloop.net/repository/webmail/rainloop-latest.zip
    dest: /usr/share/
    remote_src: yes

- name: change file modes recursively
  become: yes
  command: |
    chmod -c -R ug=rw,o=r,a-x+X /usr/share/rainloop
  args:
    warn: false
  register: chmod_status
  changed_when: chmod_status.stdout != ""

- name: change file ownership
  become: yes
  command: |
    chown -c -R apache:apache /usr/share/rainloop
  args:
    warn: false
  register: chown_status
  changed_when: chown_status.stdout != ""

- name: create configuration file
  become: yes
  template:
    src: rainloop_centos_7_conf.j2
    dest: /etc/httpd/conf.d/rainloop.conf
    backup: yes
    owner: apache
    group: apache
    mode: '0644'
  notify:
    - restart apache


#  # Configure, help
#  8) https://yourserver/rlmail/?admin/
#username: admin
#password: 12345
#  9) Change admin password
#  10) Add your domain, IMAP server, SMTP server, ...Do not use short login
#  11) Add contact support if needed. Requires DB support.
#
#  # Login to email account
#  12) https://yourserver/rlmail
#  13) Additional Tutorial
