---
- name: roundcube_setup -- ensure roundcube database is present
  mysql_db:
    login_user: root
    login_password: "{{ qmt_db_root_password}}"
    name: roundcube
    collation: utf8_bin
    state: present
  register: roundcube_database_created

- name: roundcube_setup -- reload mysql
  shell: "mysqladmin -uroot -p{{ qmt_db_root_password}} reload"

- name: roundcube_setup -- refresh mysql
  shell: "mysqladmin -uroot -p{{ qmt_db_root_password}} refresh"

- name: roundcube_setup -- create roundcube database user
  mysql_user:
    login_user: root
    login_password: "{{ qmt_db_root_password}}"
    name: roundcube
    password: "{{ qmt_db_roundcube_password}}"
    priv: "roundcube.*:ALL"
    state: present

- name: roundcube_setup -- reload mysql
  shell: "mysqladmin -uroot -p{{ qmt_db_root_password}} reload"

- name: roundcube_setup -- refresh mysql
  shell: "mysqladmin -uroot -p{{ qmt_db_root_password}} refresh"

- name: roundcube_setup -- test status of roundcube database
  shell: "mysql --defaults-extra-file={{ qmt_db_credfile }} -Bse 'use roundcube; select count(*) from session;'"
  register: probe_result

- name: roundcube_setup -- initialize the roundcube database if needed
  when: roundcube_database_created.changed or "ERROR" in probe_result.stdout
  shell: mysql --defaults-extra-file={{ qmt_db_credfile }} < /usr/share/roundcubemail/SQL/mysql.initial.sql

- name: roundcube_setup -- back up the roundcube .conf file
  become: yes
  shell: cp -p /etc/httpd/conf.d/roundcubemail.conf /etc/httpd/conf.d/roundcubemail.conf.bak

- name: roundcube_setup -- create roundcube configuration
  become: yes
  template:
    src: rc_default_config.j2
    dest: /etc/roundcubemail/config.inc.php
    backup: yes
    owner: apache
    group: apache
    mode: "0644"
  notify:
    - restart apache

- name: roundcube_setup -- create roundcube httpd configuration
  become: yes
  template:
    src: rc_httpd_config.j2
    dest: /etc/httpd/conf.d/roundcubemail.conf
    backup: yes
    owner: apache
    group: apache
    mode: "0644"
  notify:
    - restart apache

- name: roundcube_setup -- get roundcube password plugin configuration
  become: yes
  get_url:
    url: https://www.qmailtoaster.org/rc.password.config
    dest: /usr/share/roundcubemail/plugins/password/config.inc.php
    backup: yes
    mode: "0644"
  notify:
    - restart apache

- name: roundcube_setup -- ensure maximum upload size is set
  become: yes
  lineinfile:
    path: /etc/roundcubemail/config.inc.php
    regexp: "^$config['max_message_size'] = .*"
    line: "$config['max_message_size'] = '{{ qmt_attachment_size_limit }}M';"
  notify:
    - restart apache
