---
- name: install roundcube and dependencies - PHP 5
  become: yes
  when: qmt_php7_version == 0
  yum:
    name:
      - epel-release
      - php-mysql
      - roundcubemail
    state: latest
    update_cache: yes

- name: add REMI repos if needed
  become: yes
  when: qmt_php7_version != 0
  yum:
    name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present

- name: install ImageMagick
  become: yes
  when: qmt_php7_version != 0
  yum:
    name:
      - php71-php-pecl-imagick.x86_64
    enablerepo:
      - epel
      - "remi-php{{ qmt_php7_version }}"

- name: install requirements from remi's repo
  become: yes
  when: qmt_php7_version != 0
  yum:
    name:
      - php-pspell
      - php-mbstring
      - php-intl
      - php-xml
      - php-pear-Net-IDNA2
      - php-pear-Net-LDAP2
      - php-pear-Auth-SASL
      - php-pear-Net-Sieve
      - php-pear-Net-SMTP
      - php-pecl-zip
      - php-pdo
      - php-gd
    enablerepo:
      - remi
      - "remi-php{{ qmt_php7_version }}"
    disablerepo:
      - ius
      - epel
    state: latest
    update_cache: yes


- name: install roundcube and dependencies - PHP 7
  become: yes
  when: qmt_php7_version != 0
  yum:
    name:
      - roundcubemail
    enablerepo: remi-test
    disablerepo: ius
    state: latest
    update_cache: yes

- name: change ownership of roundcube sources
  become: yes
  file:
    path: /usr/share/roundcubemail
    state: directory
    recurse: yes
    owner: apache
    group: apache

- name: create roundcube database
  mysql_db:
    login_user: root
    login_password: "{{ qmt_db_root_password}}"
    name: roundcube
    state: present
    collation: utf8_bin
    encoding: utf8
  register: roundcube_database_created
  notify:
    - reload mysql
    - refresh mysql

- name: flush handlers [1]
  meta: flush_handlers

- name: create roundcube database user and assign privileges
  mysql_user:
    login_user: root
    login_password: "{{ qmt_db_root_password}}"
    name: roundcube
    password: "{{ qmt_db_roundcube_password}}"
    priv: 'roundcube.*:ALL'
    state: present
  notify:
    - reload mysql
    - refresh mysql

- name: flush handlers [2]
  meta: flush_handlers

- name: initialize roundcube database
  when: roundcube_database_created.changed
  shell: mysql -uroot -p{{ qmt_db_root_password}} roundcube < /usr/share/roundcubemail/SQL/mysql.initial.sql
  notify:
    - reload mysql
    - refresh mysql

- name: flush handlers [3]
  meta: flush_handlers

- name: create roundcube configuration
  become: yes
  template:
    src: rc_default_config.j2
    dest: /etc/roundcubemail/config.inc.php
    backup: yes
    owner: apache
    group: apache
    mode: '0644'
  notify:
    - restart apache

- name: create roundcube httpd configuration
  become: yes
  template:
    src: rc_httpd_config.j2
    dest: /etc/httpd/conf.d/roundcubemail.conf
    backup: yes
    owner: apache
    group: apache
    mode: '0644'
  notify:
    - restart apache

- name: get roundcube password plugin configuration
  become: yes
  get_url:
    url: https://www.qmailtoaster.org/rc.password.config
    dest: /usr/share/roundcubemail/plugins/password/config.inc.php
    backup: yes
    mode: '0644'
  notify:
    - restart apache

- name: Ensure maximum upload size is set
  become: yes
  lineinfile:
    path: /etc/roundcubemail/config.inc.php
    regexp: "^$config['max_message_size'] = .*"
    line: "$config['max_message_size'] = '{{ qmt_attachment_size_limit }}M';"
  notify:
    - restart apache

