---
- name: create all domains
  become: yes
  command: "/home/vpopmail/bin/vadddomain {{ item.name }} {{ item.password }}"
  ignore_errors: true
  vars:
    ansible_ssh_pipelining: yes
  with_items: "{{ qmt_domains }}"
  notify:
    - restart dovecot

- name: create catch-all file for each domain
  become: yes
  template:
    src: templates/dot_qmail_default.j2
    dest: /home/vpopmail/domains/{{ item.name }}/.qmail-default
    owner: vpopmail
    group: vchkpw
    mode: 0600
  with_items: "{{ qmt_domains }}"
  vars:
    ansible_ssh_pipelining: Yes

- name: create business role account .qmail files for each domain
  become: yes
  when: item[0].business is defined and item[0].business.action != 'none'
  template:
    src: templates/dot_qmail_business.j2
    dest: /home/vpopmail/domains/{{ item[0].name }}/.qmail-{{ item[1] }}
    owner: vpopmail
    group: vchkpw
    mode: 0644
  with_nested:
    - "{{ qmt_domains }}"
    - "{{ qmt_roles.business }}"
  vars:
    ansible_ssh_pipelining: Yes

- name: create network role account .qmail files for each domain
  become: yes
  when: item[0].network is defined and item[0].network.action != 'none'
  template:
    src: templates/dot_qmail_network.j2
    dest: /home/vpopmail/domains/{{ item[0].name }}/.qmail-{{ item[1] }}
    owner: vpopmail
    group: vchkpw
    mode: 0644
  with_nested:
    - "{{ qmt_domains }}"
    - "{{ qmt_roles.network }}"
  vars:
    ansible_ssh_pipelining: Yes

- name: create owner role account .qmail files for each domain
  become: yes
  when: item[0].owner is defined and item[0].owner.action != 'none'
  template:
    src: templates/dot_qmail_owner.j2
    dest: /home/vpopmail/domains/{{ item[0].name }}/.qmail-{{ item[1] }}
    owner: vpopmail
    group: vchkpw
    mode: 0644
  with_nested:
    - "{{ qmt_domains }}"
    - "{{ qmt_roles.owner }}"
  vars:
    ansible_ssh_pipelining: Yes

- name: create services role account .qmail files for each domain
  become: yes
  when: item[0].services is defined and item[0].services.action != 'none'
  template:
    src: templates/dot_qmail_network.j2
    dest: /home/vpopmail/domains/{{ item[0].name }}/.qmail-{{ item[1] }}
    owner: vpopmail
    group: vchkpw
    mode: 0644
  with_nested:
    - "{{ qmt_domains }}"
    - "{{ qmt_roles.services }}"
  vars:
    ansible_ssh_pipelining: Yes

- name: create webmaster role account .qmail files for each domain
  become: yes
  when: item[0].webmaster is defined and item[0].webmaster.action != 'none'
  template:
    src: templates/dot_qmail_webmaster.j2
    dest: /home/vpopmail/domains/{{ item[0].name }}/.qmail-{{ item[1] }}
    owner: vpopmail
    group: vchkpw
    mode: 0644
  with_nested:
    - "{{ qmt_domains }}"
    - "{{ qmt_roles.webmaster }}"
  vars:
    ansible_ssh_pipelining: Yes
