---
- name: create users for each domain
  become: yes
  include: create_user.yml
  loop: "{{ qmt_domains|subelements('users') }}"
  vars:
    ansible_ssh_pipelining: Yes
    domain: "{{ item.0.name }}"
    username: "{{ item.1.name }}"
    comment: "{{ item.1.comment }}"
    filter: "{{ item.1.filter }}"
    dspam: "{{ item.1.dspam }}"

