---
- name: create all domains
  become: yes
  command: "/home/vpopmail/bin/vadddomain {{ item.name }} {{ item.pass }}"
  args:
    creates: "/home/vpopmail/domains/{{ item.name }}"
  vars:
    ansible_ssh_pipelining: yes
  with_items: "{{ qmt_domains }}"

- name: create catch-all file for each domain
  become: yes
  template:
    src: templates/dot_qmail_default.j2
    dest: /home/vpopmail/domains/{{ item.name }}/.qmail-default
    owner: vpopmail
    group: vchkpw
    mode: 0600
  with_items: "{{ qmt_domains }}"
  vars:
    ansible_ssh_pipelining: Yes

- name: create owner role account .qmail files for each domain
  become: yes
  template:
    src: templates/dot_qmail_owner.j2
    dest: /home/vpopmail/domains/{{ item[0].name }}/.qmail-{{ item[1] }}
    owner: vpopmail
    group: vchkpw
    mode: 0644
  with_nested:
    - "{{ qmt_domains }}"
    - "{{ qmt_roles.owner }}"
  vars:
    ansible_ssh_pipelining: Yes
