---
- name: create all domains
  become: yes
  command: "/home/vpopmail/bin/vadddomain {{ item.name }} {{ item.pass }}"
  args:
    creates: "/home/vpopmail/domains/{{ item.name }}"
  vars:
    ansible_ssh_pipelining: Yes
  with_items: "{{ qmt_domains }}"

