---
- name: update to standard version
  become: yes
  when: qmt_package == 'standard'
  yum:
    name: '*'
    state: latest
    update_cache: yes

- name: update to testing version
  become: yes
  when: qmt_package == 'testing'
  yum:
    name: '*'
    state: latest
    update_cache: yes
    enablerepo: qmt-testing

- name: update to development version
  become: yes
  when: qmt_package == 'development'
  yum:
    name: '*'
    state: latest
    update_cache: yes
    enablerepo: qmt-devel
