---
# make sure directories and groups needed for vpopmail exist

- name: vpopmail_setup -- ensure vchkpw group exists
  become: yes
  group:
    name: vchkpw
    state: present

- name: vpopmail_setup -- ensure vpopmail user exists
  become: yes
  user:
    name: vpopmail
    comment: "Vpopmail User"
    group: vchkpw
    shell: /sbin/nologin
    home: /home/vpopmail
    state: present

- name: vpopmail_setup -- ensure vpopmail directory exists
  become: yes
  file:
    path: /home/vpopmail
    state: directory
    owner: vpopmail
    group: vchkpw
    mode: 0700

- name: vpopmail_setup -- ensure vpopmail domains directory exists
  become: yes
  file:
    path: /home/vpopmail/domains/
    state: directory
    owner: vpopmail
    group: vchkpw
    mode: 0700

- name: vpopmail_setup -- set up vpopmail.mysql
  become: yes
  template:
    src: templates/vpopmail.mysql.j2
    dest: /home/vpopmail/etc/vpopmail.mysql
    owner: vpopmail
    group: vchkpw
    mode: 0644
