- name: upload patched mrtg file
  become: yes
  copy:
    src: files/php7_fixes/usr_share_toaster_htdocs_mrtg_index.php
    dest: /usr/share/toaster/htdocs/mrtg/index.php
    owner: root
    group: apache
    mode: '0644'

- name: upload patched admin file
  become: yes
  copy:
    src: files/php7_fixes/usr_share_toaster_include_admin.inc.php
    dest: /usr/share/toaster/include/admin.inc.php
    owner: root
    group: apache
    mode: '0644'
