---
- name: add REMI repo
  become: yes
  yum:
    name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present

- name: install php7
  become: yes
  yum:
    name:
      - "php{{ qmt_php7_version }}-php-mysqlnd.x86_64"
    enablerepo:
      - remi
      - "remi-php{{ qmt_php7_version }}"
    disablerepo:
      - epel
      - ius
    state: latest
    update_cache: yes

