---
- name: update to stable version
  become: yes
  when: qmt_package == 'stable'
  yum:
    name: '*'
    state: latest
    update_cache: yes

- name: update to testing version
  become: yes
  when: qmt_package == 'testing' or qmt_package == 'development'
  yum:
    name: '*'
    state: latest
    update_cache: yes
    enablerepo: qmt-testing

- name: update to development version
  become: yes
  when: qmt_package == 'development'
  yum:
    name: '*'
    state: latest
    update_cache: yes
    enablerepo: qmt-devel
