---

- name: reboot server
  become: yes
  reboot:

- name: reload mysql
  shell: "mysqladmin -uroot -p{{ qmt_db_root_password }} reload"

- name: refresh mysql
  shell: "mysqladmin -uroot -p{{ qmt_db_root_password }} refresh"

