---

- name: reboot server
  become: yes
  reboot:

- name: reload mysql
  shell: "mysqladmin -uroot -p'{{ qmt_db_root_password }}' reload"

- name: refresh mysql
  shell: "mysqladmin -uroot -p'{{ qmt_db_root_password }}' refresh"

- name: restart firewall
  become: yes
  systemd:
    name: firewalld.service
    state: restarted

- name: restart apache
  become: yes
  systemd:
    name: httpd.service
    state: restarted

- name: rebuild qmail cdb
  become: yes
  shell: "qmailctl cdb"

- name: restart dovecot
  become: yes
  systemd:
    name: dovecot.service
    state: restarted