---

- name: reboot server
  become: yes
  reboot:

- name: reload mysql
  shell: "mysqladmin -uroot -p{{ mariadb_root_database}} reload"

- name: refresh mysql
  shell: "mysqladmin -uroot -p{{ mariadb_root_database}} refresh"

